version: '3'

services:
  chat-backend:
    image: ummarfarooqpk/talker:latest
    container_name: chat-backend
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      env_file: .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - chat-backend
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    command: |
      certonly --webroot --webroot-path=/var/www/html \
      --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email \
      --force-renewal -d talker.fun
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge