version: '3'

services:
  chat-backend:
    image: ummarfarooqpk/talker:latest
    container_name: chat-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file: 
      - ./.env
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - frontend-build:/usr/share/nginx/html/frontend
    depends_on:
      - chat-backend
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      nginx:
        condition: service_healthy
    command: certbot certonly --staging --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d talker.fun -d www.talker.fun
    restart: unless-stopped
    networks:
    - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  frontend-build:

networks:
  app-network:
    driver: bridge