const {
  PORT,
  DATABASE_URL,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  REDIS_URL,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY,
  R2_SECRET_KEY,
  R2_BUCKET_NAME,
  NODE_ENV,
  GEMINI_API_KEY,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
} = process.env;

if (
  !PORT ||
  !DATABASE_URL ||
  !ACCESS_TOKEN_SECRET ||
  !REFRESH_TOKEN_SECRET ||
  !REDIS_URL ||
  !R2_ACCOUNT_ID ||
  !R2_ACCESS_KEY ||
  !R2_SECRET_KEY ||
  !R2_BUCKET_NAME ||
  !NODE_ENV ||
  !GEMINI_API_KEY ||
  !ACCESS_TOKEN_EXPIRY ||
  !REFRESH_TOKEN_EXPIRY
) {
  throw new Error("Missing environment variables");
}

export {
  PORT,
  DATABASE_URL,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  REDIS_URL,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY,
  R2_SECRET_KEY,
  R2_BUCKET_NAME,
  NODE_ENV,
  GEMINI_API_KEY,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
};
