name: Node.js Build

on:
  push:
    branches:
      - main  # Change to your main branch name
  pull_request:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Change to your build script if needed
